version: "3.3"

services:
  app:
    container_name: node_server
    build: .
    environment:
      VIACEP_URL: https://viacep.com.br/ws
      MONGO_URL: mongodb://db:27017/cep_database
      REDIS_URL: redis://cache
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn start"
    links:
      - db
      - redis
      - db_postgres

  db:
    image: "mongo"
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  db_postgres:
    container_name: postgres_db
    image: postgres:11.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_db:/data
    environment:
      POSTGRES_DB: cep-api
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: admin
  redis:
    image: "redis"
    container_name: cache
    expose:
      - 6375
