version: "3.3"

services:
  app:
    container_name: node_server
    build: .
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn start"
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
