version: "3.3"

services:
  app:
    container_name: node_server
    build: .
    environment:
      BACK4APPCEP: https://parseapi.back4app.com/classes/Brazilzipcode_CEP
      BACK4APPID: HkH1w56yVf126H1qBQ2gvNeMiwA6Ow2etIt3VegT
      BACK4APPKEY: RgS36x0DXLNuDYDsirQbUeE85vsYybHRhevKYihS
      REDIS_URL: redis://:aoIpcQzwx1Tpu6oXfkRo4x9a0anaDqIv@redis-17621.c238.us-central1-2.gce.cloud.redislabs.com:17621
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn start"
