version: "3.3"

services:
  app:
    container_name: node_server
    build: .
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn start"
  db:
    image: "mongo"
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
