version: "3.3"

services:
  app:
    container_name: node_server
    build: .
    environment:
      VIACEP_URL: https://viacep.com.br/ws
      MONGO_URL: mongodb://db:27017/cep_database
      REDIS_URL: redis://cache
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn start"
    links:
      - db
      - redis

  db:
    image: "mongo"
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  redis:
    image: "redis"
    container_name: cache
    expose:
      - 6375
